import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, FileText, Download, ShieldAlert, CheckCircle, Info } from 'lucide-react';
import { HABDGauge } from '../components/molecules/HABDGauge';
import api from '../lib/api';
import type { AnalysisResultDto } from '../lib/adapters';
import { adaptAnalysisResult } from '../lib/adapters';

export const ReportScreen: React.FC = () => {
    const { id } = useParams<{ id: string }>(); // This would be the result ID

    const { data: result, isLoading, error } = useQuery({
        queryKey: ['report', id],
        queryFn: async () => {
            if (!id) throw new Error('No Analysis ID');
            // Assuming we added a direct fetch for a result OR we use the case ID here. 
            // In ARIA typically report is bound to case. Let's assume ID passed is caseID for now, based on previous routes context.
            const res = await api.get(`/cases/${id}/analysis/result`);
            return adaptAnalysisResult(res.data.data);
        },
        enabled: !!id,
    });

    if (isLoading) {
        return (
            <div className="flex items-center justify-center py-20">
                <div className="w-8 h-8 border-2 border-navy-200 border-t-navy-600 rounded-full animate-spin" />
            </div>
        );
    }

    if (error || !result) {
        return (
            <div className="p-8 text-center">
                <ShieldAlert className="w-12 h-12 text-slate-300 mx-auto mb-4" />
                <h2 className="text-lg font-bold text-slate-700">Report Unavailable</h2>
                <p className="text-slate-500 mt-2">Could not load the analysis data. It may not be complete.</p>
                <Link to="/" className="aria-btn-secondary mt-6">Return to Dashboard</Link>
            </div>
        );
    }

    return (
        <div className="max-w-5xl mx-auto animate-fade-in space-y-6">
            <div className="flex items-center gap-3">
                <Link to={`/cases/${id}`} className="aria-btn-ghost p-2">
                    <ArrowLeft className="w-4 h-4" />
                </Link>
                <div className="flex-1">
                    <h1 className="text-xl font-bold text-slate-800">Attribution Analysis Report</h1>
                    <p className="text-sm text-slate-500 font-mono">Job Reference: {result.jobId}</p>
                </div>
                <button className="aria-btn-primary">
                    <Download className="w-4 h-4" /> Export PDF
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                {/* Visual Overview */}
                <div className="aria-card p-8 flex flex-col items-center justify-center md:col-span-1 border-navy-100 bg-gradient-to-b from-white to-slate-50">
                    <HABDGauge
                        score={result.score}
                        confidenceLow={result.confidenceLow}
                        confidenceHigh={result.confidenceHigh}
                        mimicryFlag={result.mimicryFlag}
                    />
                </div>

                {/* Executive Summary */}
                <div className="aria-card p-6 md:col-span-2 flex flex-col">
                    <h2 className="text-sm font-semibold text-slate-700 flex items-center gap-2 mb-4">
                        <FileText className="w-4 h-4 text-navy-600" />
                        Executive Summary
                    </h2>
                    <div className="prose prose-sm prose-slate max-w-none flex-1">
                        {result.executiveSummary ? (
                            <p className="leading-relaxed text-slate-700">{result.executiveSummary}</p>
                        ) : (
                            <p className="text-slate-400 italic">No summary generated by the engine.</p>
                        )}

                        {result.agentProfileNotes && (
                            <div className="mt-6 p-4 rounded-md bg-navy-50 border border-navy-100">
                                <h4 className="font-semibold text-navy-800 text-xs uppercase tracking-wide mb-2">Agent Profile Indicator</h4>
                                <p className="text-navy-700">{result.agentProfileNotes}</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Dimensional Breakdown */}
            <div className="space-y-4">
                <h3 className="text-lg font-bold text-slate-800 pt-4">Behavioral Dimensions</h3>

                {result.dimensions.map((dim, i) => (
                    <div key={i} className="aria-card overflow-hidden">
                        <div className="p-5 border-b border-slate-100 bg-slate-50 flex items-center justify-between">
                            <div>
                                <h4 className="font-semibold text-slate-800">{dim.displayName || dim.name}</h4>
                                <p className="text-xs text-slate-500 mt-1">
                                    Confidence Rating: <span className="font-medium text-slate-700">{(dim.confidence * 100).toFixed(0)}%</span>
                                </p>
                            </div>
                            <div className="text-right">
                                <div className="text-2xl font-bold" style={{ color: dim.score < 30 ? '#EF4444' : dim.score > 70 ? '#10B981' : '#F59E0B' }}>
                                    {dim.score}
                                </div>
                                <div className="text-xs text-slate-400 uppercase tracking-widest font-semibold mt-1">Score</div>
                            </div>
                        </div>

                        <div className="p-0">
                            {dim.evidence && dim.evidence.length > 0 ? (
                                <table className="aria-table">
                                    <thead>
                                        <tr>
                                            <th className="w-1/4">Marker Type</th>
                                            <th className="w-1/6">Severity</th>
                                            <th>Evidence Details</th>
                                            <th className="w-32 text-right">Offset (ms)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {dim.evidence.map((ev, idx) => (
                                            <tr key={idx}>
                                                <td className="font-mono text-xs">{ev.type}</td>
                                                <td>
                                                    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${ev.severity === 'critical' || ev.severity === 'high' ? 'bg-red-50 text-red-700' :
                                                            ev.severity === 'medium' ? 'bg-amber-50 text-amber-700' :
                                                                'bg-slate-100 text-slate-700'
                                                        }`}>
                                                        {ev.severity.toUpperCase()}
                                                    </span>
                                                </td>
                                                <td className="text-slate-600 truncate max-w-md" title={ev.description}>
                                                    {ev.description}
                                                </td>
                                                <td className="text-right text-slate-500 font-mono text-xs text-right">
                                                    +{ev.timestampOffsetMs}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            ) : (
                                <div className="p-8 text-center flex flex-col items-center">
                                    <Info className="w-6 h-6 text-slate-300 mb-2" />
                                    <p className="text-sm text-slate-500">No explicit evidence markers highlighted for this dimension.</p>
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            <div className="pb-16" />
        </div>
    );
};
