import pinoHttp from 'pino-http';
import { logger } from '../utils/logger';

/**
 * ARIA — HTTP Request Logger Middleware
 *
 * Replaces `morgan('combined')` with structured JSON request logging via pino-http.
 *
 * Every incoming request gets:
 *   - A unique `requestId` (generated by pino-http, or forwarded from X-Request-Id header)
 *   - A child logger bound to that requestId (accessible via `req.log`)
 *   - Automatic request/response logging with duration, status, method, url
 *
 * Usage in downstream middleware/handlers:
 *   req.log.info({ caseId }, 'Case fetched');
 *   // → { requestId: "abc-123", caseId: "...", msg: "Case fetched", ... }
 */
export const requestLogger = pinoHttp({
    logger,

    // Use X-Request-Id header if present, otherwise generate a UUID
    genReqId: (req) => {
        return (req.headers['x-request-id'] as string) || crypto.randomUUID();
    },

    // Custom log level based on response status code
    customLogLevel: (_req, res, err) => {
        if (err || (res.statusCode && res.statusCode >= 500)) return 'error';
        if (res.statusCode && res.statusCode >= 400) return 'warn';
        return 'info';
    },

    // Don't log health-check requests (noisy in production)
    autoLogging: {
        ignore: (req) => req.url === '/api/v1/health',
    },

    // Custom success message
    customSuccessMessage: (req, res) => {
        return `${req.method} ${req.url} → ${res.statusCode}`;
    },

    // Custom error message
    customErrorMessage: (_req, res) => {
        return `Request failed with status ${res.statusCode}`;
    },

    // Attach requestId to response header for client debugging
    customProps: (req) => {
        return {
            requestId: req.id,
        };
    },
});
